services:
  solochain:
    image: solochain-node:latest
    container_name: solochain
    command:
      - --dev
      - --rpc-cors=all
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --base-path
      - /data
    ports:
      # ws port 9944
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    volumes:
      - solochain-data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_FULL_NAME}
    volumes:
      - ./indexer/db/timescale.sql:/mnt/timescale.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    container_name: indexer
    depends_on:
      db:
        condition: service_healthy
      solochain:
        condition: service_started
    environment:
      Env: ${ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SOLOCHAIN_RPC: ws://solochain:9944
    ports:
      - "${INDEXER_PORT}:${INDEXER_PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      APP_ENV: ${ENV}
      SERVER_URL: http://localhost:${INDEXER_PORT}
    restart: unless-stopped

volumes:
  pgdata:
  solochain-data:

