services:
  solochain:
    image: solochain-node:latest
    container_name: solochain
    command:
      - --dev
      - --rpc-cors=all
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --base-path
      - /data
    ports:
      # ws port 9944
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    volumes:
      - solochain-data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./indexer/db/timescale.sql:/mnt/timescale.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    container_name: indexer
    depends_on:
      timescaledb:
        condition: service_healthy
      solochain:
        condition: service_started
    environment:
      Env: ${ENV}
      NODE_WS_URL: ws://solochain:9944
      DATABASE_URL: postgres://postgres:password@timescaledb:5432/${POSTGRES_DB_FULL_NAME}
      RUST_LOG: indexer=debug,info
    ports:
      - "8081:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  tradebot:
    build:
      context: .
      dockerfile: tradebot/Dockerfile
    container_name: tradebot
    depends_on:
      timescaledb:
        condition: service_healthy
      solochain:
        condition: service_started
    env_file:
      - ./tradebot/.env
    volumes:
      - ./tradebot/ETHUSDC_2025-11-12T22-08-37-339Z_synthetic_blocks.jsonl:/app/ETHUSDC_2025-11-12T22-08-37-339Z_synthetic_blocks.jsonl:ro
    restart: unless-stopped

volumes:
  pgdata:
  solochain-data:
