services:
  solochain:
    image: solochain-node:latest
    container_name: solochain
    command:
      - --dev
      - --rpc-cors=all
      - --rpc-methods=Unsafe
      - --unsafe-rpc-external
      - --base-path
      - /data
    ports:
      # ws port 9944
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    volumes:
      - solochain-data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./indexer/db/timescale.sql:/mnt/timescale.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    container_name: indexer
    depends_on:
      timescaledb:
        condition: service_healthy
      solochain:
        condition: service_started
    environment:
      Env: ${ENV}
      NODE_WS_URL: ws://solochain:9944
      DATABASE_URL: postgres://postgres:password@timescaledb:5432/${POSTGRES_DB_FULL_NAME}
      RUST_LOG: indexer=debug,info
    ports:
      - "${INDEXER_PORT}:${INDEXER_PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      APP_ENV: ${ENV}
      SERVER_URL: http://localhost:${INDEXER_PORT}
    restart: unless-stopped

  # db:
  #   image: postgres:15
  #   container_name: indexer-postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB_FULL_NAME}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  pgdata:
  solochain-data: